// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(restsendFFI)
import restsendFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_restsend_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_restsend_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_PANIC: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: nil)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_PANIC:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
                throw CancellationError()

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.


fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public protocol RsClientProtocol {
    func appActive()  
    func appDeactivate()  
    func connect(callback: RsCallback) async 
    func getConversation(topicId: String)   -> Conversation?
    func removeConversation(topicId: String)  
    func setConversationMute(topicId: String, mute: Bool)  
    func setConversationRead(topicId: String)  
    func setConversationSticky(topicId: String, sticky: Bool)  
    func shutdown()  
    func syncConversations(updatedAt: String?, limit: UInt32, callback: RsSyncConversationsCallback)  
    
}

public class RsClient: RsClientProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }
    public convenience init(rootPath: String, dbName: String, info: AuthInfo)  {
        self.init(unsafeFromRawPointer: try! rustCall() {
    uniffi_restsend_ffi_fn_constructor_rsclient_new(
        FfiConverterString.lower(rootPath),
        FfiConverterString.lower(dbName),
        FfiConverterTypeAuthInfo_lower(info),$0)
})
    }

    deinit {
        try! rustCall { uniffi_restsend_ffi_fn_free_rsclient(pointer, $0) }
    }

    

    
    

    public func appActive()  {
        try! 
    rustCall() {
    
    uniffi_restsend_ffi_fn_method_rsclient_app_active(self.pointer, $0
    )
}
    }

    public func appDeactivate()  {
        try! 
    rustCall() {
    
    uniffi_restsend_ffi_fn_method_rsclient_app_deactivate(self.pointer, $0
    )
}
    }

    public func connect(callback: RsCallback) async  {
        return try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_restsend_ffi_fn_method_rsclient_connect(
                    self.pointer,
                    FfiConverterCallbackInterfaceRsCallback.lower(callback)
                )
            },
            pollFunc: ffi_restsend_ffi_rust_future_poll_void,
            completeFunc: ffi_restsend_ffi_rust_future_complete_void,
            freeFunc: ffi_restsend_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
    }

    

    public func getConversation(topicId: String)  -> Conversation? {
        return try!  FfiConverterOptionTypeConversation.lift(
            try! 
    rustCall() {
    
    uniffi_restsend_ffi_fn_method_rsclient_get_conversation(self.pointer, 
        FfiConverterString.lower(topicId),$0
    )
}
        )
    }

    public func removeConversation(topicId: String)  {
        try! 
    rustCall() {
    
    uniffi_restsend_ffi_fn_method_rsclient_remove_conversation(self.pointer, 
        FfiConverterString.lower(topicId),$0
    )
}
    }

    public func setConversationMute(topicId: String, mute: Bool)  {
        try! 
    rustCall() {
    
    uniffi_restsend_ffi_fn_method_rsclient_set_conversation_mute(self.pointer, 
        FfiConverterString.lower(topicId),
        FfiConverterBool.lower(mute),$0
    )
}
    }

    public func setConversationRead(topicId: String)  {
        try! 
    rustCall() {
    
    uniffi_restsend_ffi_fn_method_rsclient_set_conversation_read(self.pointer, 
        FfiConverterString.lower(topicId),$0
    )
}
    }

    public func setConversationSticky(topicId: String, sticky: Bool)  {
        try! 
    rustCall() {
    
    uniffi_restsend_ffi_fn_method_rsclient_set_conversation_sticky(self.pointer, 
        FfiConverterString.lower(topicId),
        FfiConverterBool.lower(sticky),$0
    )
}
    }

    public func shutdown()  {
        try! 
    rustCall() {
    
    uniffi_restsend_ffi_fn_method_rsclient_shutdown(self.pointer, $0
    )
}
    }

    public func syncConversations(updatedAt: String?, limit: UInt32, callback: RsSyncConversationsCallback)  {
        try! 
    rustCall() {
    
    uniffi_restsend_ffi_fn_method_rsclient_sync_conversations(self.pointer, 
        FfiConverterOptionString.lower(updatedAt),
        FfiConverterUInt32.lower(limit),
        FfiConverterCallbackInterfaceRsSyncConversationsCallback.lower(callback),$0
    )
}
    }
}

public struct FfiConverterTypeRsClient: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = RsClient

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RsClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: RsClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> RsClient {
        return RsClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: RsClient) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}


public func FfiConverterTypeRsClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> RsClient {
    return try FfiConverterTypeRsClient.lift(pointer)
}

public func FfiConverterTypeRsClient_lower(_ value: RsClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeRsClient.lower(value)
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate typealias UniFFICallbackHandle = UInt64
fileprivate class UniFFICallbackHandleMap<T> {
    private var leftMap: [UniFFICallbackHandle: T] = [:]
    private var counter: [UniFFICallbackHandle: UInt64] = [:]
    private var rightMap: [ObjectIdentifier: UniFFICallbackHandle] = [:]

    private let lock = NSLock()
    private var currentHandle: UniFFICallbackHandle = 0
    private let stride: UniFFICallbackHandle = 1

    func insert(obj: T) -> UniFFICallbackHandle {
        lock.withLock {
            let id = ObjectIdentifier(obj as AnyObject)
            let handle = rightMap[id] ?? {
                currentHandle += stride
                let handle = currentHandle
                leftMap[handle] = obj
                rightMap[id] = handle
                return handle
            }()
            counter[handle] = (counter[handle] ?? 0) + 1
            return handle
        }
    }

    func get(handle: UniFFICallbackHandle) -> T? {
        lock.withLock {
            leftMap[handle]
        }
    }

    func delete(handle: UniFFICallbackHandle) {
        remove(handle: handle)
    }

    @discardableResult
    func remove(handle: UniFFICallbackHandle) -> T? {
        lock.withLock {
            defer { counter[handle] = (counter[handle] ?? 1) - 1 }
            guard counter[handle] == 1 else { return leftMap[handle] }
            let obj = leftMap.removeValue(forKey: handle)
            if let obj = obj {
                rightMap.removeValue(forKey: ObjectIdentifier(obj as AnyObject))
            }
            return obj
        }
    }
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Declaration and FfiConverters for RsCallback Callback Interface

public protocol RsCallback : AnyObject {
    func onConnected() 
    func onConnecting() 
    func onTokenExpired(reason: String) 
    func onNetBroken(reason: String) 
    func onKickoffByOtherClient(reason: String) 
    func onSystemRequest(req: ChatRequest)  -> ChatRequest?
    func onUnknownRequest(req: ChatRequest)  -> ChatRequest?
    func onTopicTyping(topicId: String, message: String?) 
    func onNewMessage(topicId: String, message: ChatRequest)  -> Bool
    func onTopicRead(topicId: String, message: ChatRequest) 
    func onConversationsUpdated(conversations: [Conversation]) 
    func onConversationsRemoved(conversatioId: String) 
    
}

// The ForeignCallback that is passed to Rust.
fileprivate let foreignCallbackCallbackInterfaceRsCallback : ForeignCallback =
    { (handle: UniFFICallbackHandle, method: Int32, argsData: UnsafePointer<UInt8>, argsLen: Int32, out_buf: UnsafeMutablePointer<RustBuffer>) -> Int32 in
    

    func invokeOnConnected(_ swiftCallbackInterface: RsCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        func makeCall() throws -> Int32 {
            try swiftCallbackInterface.onConnected(
                    )
            return UNIFFI_CALLBACK_SUCCESS
        }
        return try makeCall()
    }

    func invokeOnConnecting(_ swiftCallbackInterface: RsCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        func makeCall() throws -> Int32 {
            try swiftCallbackInterface.onConnecting(
                    )
            return UNIFFI_CALLBACK_SUCCESS
        }
        return try makeCall()
    }

    func invokeOnTokenExpired(_ swiftCallbackInterface: RsCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        var reader = createReader(data: Data(bytes: argsData, count: Int(argsLen)))
        func makeCall() throws -> Int32 {
            try swiftCallbackInterface.onTokenExpired(
                    reason:  try FfiConverterString.read(from: &reader)
                    )
            return UNIFFI_CALLBACK_SUCCESS
        }
        return try makeCall()
    }

    func invokeOnNetBroken(_ swiftCallbackInterface: RsCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        var reader = createReader(data: Data(bytes: argsData, count: Int(argsLen)))
        func makeCall() throws -> Int32 {
            try swiftCallbackInterface.onNetBroken(
                    reason:  try FfiConverterString.read(from: &reader)
                    )
            return UNIFFI_CALLBACK_SUCCESS
        }
        return try makeCall()
    }

    func invokeOnKickoffByOtherClient(_ swiftCallbackInterface: RsCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        var reader = createReader(data: Data(bytes: argsData, count: Int(argsLen)))
        func makeCall() throws -> Int32 {
            try swiftCallbackInterface.onKickoffByOtherClient(
                    reason:  try FfiConverterString.read(from: &reader)
                    )
            return UNIFFI_CALLBACK_SUCCESS
        }
        return try makeCall()
    }

    func invokeOnSystemRequest(_ swiftCallbackInterface: RsCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        var reader = createReader(data: Data(bytes: argsData, count: Int(argsLen)))
        func makeCall() throws -> Int32 {
            let result =  swiftCallbackInterface.onSystemRequest(
                    req:  try FfiConverterTypeChatRequest.read(from: &reader)
                    )
            var writer = [UInt8]()
            FfiConverterOptionTypeChatRequest.write(result, into: &writer)
            out_buf.pointee = RustBuffer(bytes: writer)
            return UNIFFI_CALLBACK_SUCCESS
        }
        return try makeCall()
    }

    func invokeOnUnknownRequest(_ swiftCallbackInterface: RsCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        var reader = createReader(data: Data(bytes: argsData, count: Int(argsLen)))
        func makeCall() throws -> Int32 {
            let result =  swiftCallbackInterface.onUnknownRequest(
                    req:  try FfiConverterTypeChatRequest.read(from: &reader)
                    )
            var writer = [UInt8]()
            FfiConverterOptionTypeChatRequest.write(result, into: &writer)
            out_buf.pointee = RustBuffer(bytes: writer)
            return UNIFFI_CALLBACK_SUCCESS
        }
        return try makeCall()
    }

    func invokeOnTopicTyping(_ swiftCallbackInterface: RsCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        var reader = createReader(data: Data(bytes: argsData, count: Int(argsLen)))
        func makeCall() throws -> Int32 {
            try swiftCallbackInterface.onTopicTyping(
                    topicId:  try FfiConverterString.read(from: &reader), 
                    message:  try FfiConverterOptionString.read(from: &reader)
                    )
            return UNIFFI_CALLBACK_SUCCESS
        }
        return try makeCall()
    }

    func invokeOnNewMessage(_ swiftCallbackInterface: RsCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        var reader = createReader(data: Data(bytes: argsData, count: Int(argsLen)))
        func makeCall() throws -> Int32 {
            let result =  swiftCallbackInterface.onNewMessage(
                    topicId:  try FfiConverterString.read(from: &reader), 
                    message:  try FfiConverterTypeChatRequest.read(from: &reader)
                    )
            var writer = [UInt8]()
            FfiConverterBool.write(result, into: &writer)
            out_buf.pointee = RustBuffer(bytes: writer)
            return UNIFFI_CALLBACK_SUCCESS
        }
        return try makeCall()
    }

    func invokeOnTopicRead(_ swiftCallbackInterface: RsCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        var reader = createReader(data: Data(bytes: argsData, count: Int(argsLen)))
        func makeCall() throws -> Int32 {
            try swiftCallbackInterface.onTopicRead(
                    topicId:  try FfiConverterString.read(from: &reader), 
                    message:  try FfiConverterTypeChatRequest.read(from: &reader)
                    )
            return UNIFFI_CALLBACK_SUCCESS
        }
        return try makeCall()
    }

    func invokeOnConversationsUpdated(_ swiftCallbackInterface: RsCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        var reader = createReader(data: Data(bytes: argsData, count: Int(argsLen)))
        func makeCall() throws -> Int32 {
            try swiftCallbackInterface.onConversationsUpdated(
                    conversations:  try FfiConverterSequenceTypeConversation.read(from: &reader)
                    )
            return UNIFFI_CALLBACK_SUCCESS
        }
        return try makeCall()
    }

    func invokeOnConversationsRemoved(_ swiftCallbackInterface: RsCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        var reader = createReader(data: Data(bytes: argsData, count: Int(argsLen)))
        func makeCall() throws -> Int32 {
            try swiftCallbackInterface.onConversationsRemoved(
                    conversatioId:  try FfiConverterString.read(from: &reader)
                    )
            return UNIFFI_CALLBACK_SUCCESS
        }
        return try makeCall()
    }


    switch method {
        case IDX_CALLBACK_FREE:
            FfiConverterCallbackInterfaceRsCallback.drop(handle: handle)
            // Sucessful return
            // See docs of ForeignCallback in `uniffi_core/src/ffi/foreigncallbacks.rs`
            return UNIFFI_CALLBACK_SUCCESS
        case 1:
            let cb: RsCallback
            do {
                cb = try FfiConverterCallbackInterfaceRsCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("RSCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeOnConnected(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        case 2:
            let cb: RsCallback
            do {
                cb = try FfiConverterCallbackInterfaceRsCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("RSCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeOnConnecting(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        case 3:
            let cb: RsCallback
            do {
                cb = try FfiConverterCallbackInterfaceRsCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("RSCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeOnTokenExpired(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        case 4:
            let cb: RsCallback
            do {
                cb = try FfiConverterCallbackInterfaceRsCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("RSCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeOnNetBroken(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        case 5:
            let cb: RsCallback
            do {
                cb = try FfiConverterCallbackInterfaceRsCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("RSCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeOnKickoffByOtherClient(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        case 6:
            let cb: RsCallback
            do {
                cb = try FfiConverterCallbackInterfaceRsCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("RSCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeOnSystemRequest(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        case 7:
            let cb: RsCallback
            do {
                cb = try FfiConverterCallbackInterfaceRsCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("RSCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeOnUnknownRequest(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        case 8:
            let cb: RsCallback
            do {
                cb = try FfiConverterCallbackInterfaceRsCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("RSCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeOnTopicTyping(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        case 9:
            let cb: RsCallback
            do {
                cb = try FfiConverterCallbackInterfaceRsCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("RSCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeOnNewMessage(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        case 10:
            let cb: RsCallback
            do {
                cb = try FfiConverterCallbackInterfaceRsCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("RSCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeOnTopicRead(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        case 11:
            let cb: RsCallback
            do {
                cb = try FfiConverterCallbackInterfaceRsCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("RSCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeOnConversationsUpdated(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        case 12:
            let cb: RsCallback
            do {
                cb = try FfiConverterCallbackInterfaceRsCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("RSCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeOnConversationsRemoved(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        
        // This should never happen, because an out of bounds method index won't
        // ever be used. Once we can catch errors, we should return an InternalError.
        // https://github.com/mozilla/uniffi-rs/issues/351
        default:
            // An unexpected error happened.
            // See docs of ForeignCallback in `uniffi_core/src/ffi/foreigncallbacks.rs`
            return UNIFFI_CALLBACK_UNEXPECTED_ERROR
    }
}

// FfiConverter protocol for callback interfaces
fileprivate struct FfiConverterCallbackInterfaceRsCallback {
    private static let initCallbackOnce: () = {
        // Swift ensures this initializer code will once run once, even when accessed by multiple threads.
        try! rustCall { (err: UnsafeMutablePointer<RustCallStatus>) in
            uniffi_restsend_ffi_fn_init_callback_rscallback(foreignCallbackCallbackInterfaceRsCallback, err)
        }
    }()

    private static func ensureCallbackinitialized() {
        _ = initCallbackOnce
    }

    static func drop(handle: UniFFICallbackHandle) {
        handleMap.remove(handle: handle)
    }

    private static var handleMap = UniFFICallbackHandleMap<RsCallback>()
}

extension FfiConverterCallbackInterfaceRsCallback : FfiConverter {
    typealias SwiftType = RsCallback
    // We can use Handle as the FfiType because it's a typealias to UInt64
    typealias FfiType = UniFFICallbackHandle

    public static func lift(_ handle: UniFFICallbackHandle) throws -> SwiftType {
        ensureCallbackinitialized();
        guard let callback = handleMap.get(handle: handle) else {
            throw UniffiInternalError.unexpectedStaleHandle
        }
        return callback
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        ensureCallbackinitialized();
        let handle: UniFFICallbackHandle = try readInt(&buf)
        return try lift(handle)
    }

    public static func lower(_ v: SwiftType) -> UniFFICallbackHandle {
        ensureCallbackinitialized();
        return handleMap.insert(obj: v)
    }

    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        ensureCallbackinitialized();
        writeInt(&buf, lower(v))
    }
}



// Declaration and FfiConverters for RsSyncConversationsCallback Callback Interface

public protocol RsSyncConversationsCallback : AnyObject {
    func onSuccess(r: GetConversationsResult) 
    func onFail(e: ClientError) 
    
}

// The ForeignCallback that is passed to Rust.
fileprivate let foreignCallbackCallbackInterfaceRsSyncConversationsCallback : ForeignCallback =
    { (handle: UniFFICallbackHandle, method: Int32, argsData: UnsafePointer<UInt8>, argsLen: Int32, out_buf: UnsafeMutablePointer<RustBuffer>) -> Int32 in
    

    func invokeOnSuccess(_ swiftCallbackInterface: RsSyncConversationsCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        var reader = createReader(data: Data(bytes: argsData, count: Int(argsLen)))
        func makeCall() throws -> Int32 {
            try swiftCallbackInterface.onSuccess(
                    r:  try FfiConverterTypeGetConversationsResult.read(from: &reader)
                    )
            return UNIFFI_CALLBACK_SUCCESS
        }
        return try makeCall()
    }

    func invokeOnFail(_ swiftCallbackInterface: RsSyncConversationsCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        var reader = createReader(data: Data(bytes: argsData, count: Int(argsLen)))
        func makeCall() throws -> Int32 {
            try swiftCallbackInterface.onFail(
                    e:  try FfiConverterTypeClientError.read(from: &reader)
                    )
            return UNIFFI_CALLBACK_SUCCESS
        }
        return try makeCall()
    }


    switch method {
        case IDX_CALLBACK_FREE:
            FfiConverterCallbackInterfaceRsSyncConversationsCallback.drop(handle: handle)
            // Sucessful return
            // See docs of ForeignCallback in `uniffi_core/src/ffi/foreigncallbacks.rs`
            return UNIFFI_CALLBACK_SUCCESS
        case 1:
            let cb: RsSyncConversationsCallback
            do {
                cb = try FfiConverterCallbackInterfaceRsSyncConversationsCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("RSSyncConversationsCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeOnSuccess(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        case 2:
            let cb: RsSyncConversationsCallback
            do {
                cb = try FfiConverterCallbackInterfaceRsSyncConversationsCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("RSSyncConversationsCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeOnFail(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        
        // This should never happen, because an out of bounds method index won't
        // ever be used. Once we can catch errors, we should return an InternalError.
        // https://github.com/mozilla/uniffi-rs/issues/351
        default:
            // An unexpected error happened.
            // See docs of ForeignCallback in `uniffi_core/src/ffi/foreigncallbacks.rs`
            return UNIFFI_CALLBACK_UNEXPECTED_ERROR
    }
}

// FfiConverter protocol for callback interfaces
fileprivate struct FfiConverterCallbackInterfaceRsSyncConversationsCallback {
    private static let initCallbackOnce: () = {
        // Swift ensures this initializer code will once run once, even when accessed by multiple threads.
        try! rustCall { (err: UnsafeMutablePointer<RustCallStatus>) in
            uniffi_restsend_ffi_fn_init_callback_rssyncconversationscallback(foreignCallbackCallbackInterfaceRsSyncConversationsCallback, err)
        }
    }()

    private static func ensureCallbackinitialized() {
        _ = initCallbackOnce
    }

    static func drop(handle: UniFFICallbackHandle) {
        handleMap.remove(handle: handle)
    }

    private static var handleMap = UniFFICallbackHandleMap<RsSyncConversationsCallback>()
}

extension FfiConverterCallbackInterfaceRsSyncConversationsCallback : FfiConverter {
    typealias SwiftType = RsSyncConversationsCallback
    // We can use Handle as the FfiType because it's a typealias to UInt64
    typealias FfiType = UniFFICallbackHandle

    public static func lift(_ handle: UniFFICallbackHandle) throws -> SwiftType {
        ensureCallbackinitialized();
        guard let callback = handleMap.get(handle: handle) else {
            throw UniffiInternalError.unexpectedStaleHandle
        }
        return callback
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        ensureCallbackinitialized();
        let handle: UniFFICallbackHandle = try readInt(&buf)
        return try lift(handle)
    }

    public static func lower(_ v: SwiftType) -> UniFFICallbackHandle {
        ensureCallbackinitialized();
        return handleMap.insert(obj: v)
    }

    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        ensureCallbackinitialized();
        writeInt(&buf, lower(v))
    }
}

fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterOptionTypeAuthInfo: FfiConverterRustBuffer {
    typealias SwiftType = AuthInfo?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAuthInfo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAuthInfo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterOptionTypeChatRequest: FfiConverterRustBuffer {
    typealias SwiftType = ChatRequest?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeChatRequest.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeChatRequest.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterOptionTypeConversation: FfiConverterRustBuffer {
    typealias SwiftType = Conversation?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeConversation.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeConversation.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterSequenceTypeConversation: FfiConverterRustBuffer {
    typealias SwiftType = [Conversation]

    public static func write(_ value: [Conversation], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeConversation.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Conversation] {
        let len: Int32 = try readInt(&buf)
        var seq = [Conversation]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeConversation.read(from: &buf))
        }
        return seq
    }
}










private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UnsafeMutableRawPointer,
    pollFunc: (UnsafeMutableRawPointer, UnsafeMutableRawPointer) -> (),
    completeFunc: (UnsafeMutableRawPointer, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UnsafeMutableRawPointer) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) async throws -> T {
    // Make sure to call uniffiEnsureInitialized() since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(rustFuture, ContinuationHolder($0).toOpaque())
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(ptr: UnsafeMutableRawPointer, pollResult: Int8) {
    ContinuationHolder.fromOpaque(ptr).resume(pollResult)
}

// Wraps UnsafeContinuation in a class so that we can use reference counting when passing it across
// the FFI
fileprivate class ContinuationHolder {
    let continuation: UnsafeContinuation<Int8, Never>

    init(_ continuation: UnsafeContinuation<Int8, Never>) {
        self.continuation = continuation
    }

    func resume(_ pollResult: Int8) {
        self.continuation.resume(returning: pollResult)
    }

    func toOpaque() -> UnsafeMutableRawPointer {
        return Unmanaged<ContinuationHolder>.passRetained(self).toOpaque()
    }

    static func fromOpaque(_ ptr: UnsafeRawPointer) -> ContinuationHolder {
        return Unmanaged<ContinuationHolder>.fromOpaque(ptr).takeRetainedValue()
    }
}

fileprivate func uniffiInitContinuationCallback() {
    ffi_restsend_ffi_rust_future_continuation_callback_set(uniffiFutureContinuationCallback)
}

public func getCurrentUser(rootPath: String)  -> AuthInfo? {
    return try!  FfiConverterOptionTypeAuthInfo.lift(
        try! rustCall() {
    uniffi_restsend_ffi_fn_func_get_current_user(
        FfiConverterString.lower(rootPath),$0)
}
    )
}

public func initLog(level: String, isTest: Bool)  {
    try! rustCall() {
    uniffi_restsend_ffi_fn_func_init_log(
        FfiConverterString.lower(level),
        FfiConverterBool.lower(isTest),$0)
}
}



public func login(endpoint: String, userId: String, password: String) async throws -> AuthInfo {
    return try  await uniffiRustCallAsync(
        rustFutureFunc: {
            uniffi_restsend_ffi_fn_func_login(
                FfiConverterString.lower(endpoint),
                FfiConverterString.lower(userId),
                FfiConverterString.lower(password)
            )
        },
        pollFunc: ffi_restsend_ffi_rust_future_poll_rust_buffer,
        completeFunc: ffi_restsend_ffi_rust_future_complete_rust_buffer,
        freeFunc: ffi_restsend_ffi_rust_future_free_rust_buffer,
        liftFunc: FfiConverterTypeAuthInfo_lift,
        errorHandler: FfiConverterTypeClientError.lift
    )
}



public func setCurrentUser(rootPath: String, userId: String)  {
    try! rustCall() {
    uniffi_restsend_ffi_fn_func_set_current_user(
        FfiConverterString.lower(rootPath),
        FfiConverterString.lower(userId),$0)
}
}



private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variables to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 24
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_restsend_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_restsend_ffi_checksum_func_get_current_user() != 45482) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_func_init_log() != 43858) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_func_login() != 12757) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_func_set_current_user() != 42727) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rsclient_app_active() != 51400) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rsclient_app_deactivate() != 39678) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rsclient_connect() != 58786) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rsclient_get_conversation() != 27970) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rsclient_remove_conversation() != 54892) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rsclient_set_conversation_mute() != 37431) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rsclient_set_conversation_read() != 22336) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rsclient_set_conversation_sticky() != 55288) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rsclient_shutdown() != 41772) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rsclient_sync_conversations() != 1803) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_constructor_rsclient_new() != 64553) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rscallback_on_connected() != 42584) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rscallback_on_connecting() != 4066) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rscallback_on_token_expired() != 52425) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rscallback_on_net_broken() != 39527) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rscallback_on_kickoff_by_other_client() != 13977) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rscallback_on_system_request() != 16118) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rscallback_on_unknown_request() != 11827) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rscallback_on_topic_typing() != 51622) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rscallback_on_new_message() != 46405) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rscallback_on_topic_read() != 43005) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rscallback_on_conversations_updated() != 54859) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rscallback_on_conversations_removed() != 23446) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rssyncconversationscallback_on_success() != 39325) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_restsend_ffi_checksum_method_rssyncconversationscallback_on_fail() != 35938) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiInitContinuationCallback()
    return InitializationResult.ok
}

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}