// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/restsend_sdk/models/user.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Signin with userId and password or token
Future<AuthInfo> signin(
        {required String endpoint,
        required String userId,
        String? password,
        String? token}) =>
    RustLib.instance.api.crateClientAccountSignin(
        endpoint: endpoint, userId: userId, password: password, token: token);

Future<String> hello() => RustLib.instance.api.crateClientAccountHello();

/// Signup with userId and password
Future<AuthInfo> signup(
        {required String endpoint,
        required String userId,
        required String password}) =>
    RustLib.instance.api.crateClientAccountSignup(
        endpoint: endpoint, userId: userId, password: password);

/// Logout with token
Future<void> logout({required String endpoint, required String token}) =>
    RustLib.instance.api
        .crateClientAccountLogout(endpoint: endpoint, token: token);
