// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `CallbackDartWrap`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `on_connected`, `on_connecting`, `on_conversation_removed`, `on_conversations_updated`, `on_kickoff_by_other_client`, `on_net_broken`, `on_new_message`, `on_system_request`, `on_token_expired`, `on_topic_read`, `on_topic_typing`, `on_unknown_request`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < dyn Fn () + Send + Sync >>>
abstract class BoxFn implements RustOpaqueInterface {}
