// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/restsend_sdk/models/user.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> setLogging({required String level}) =>
    RustLib.instance.api.crateClientClientSetLogging(level: level);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Client>>
abstract class Client implements RustOpaqueInterface {
  /// connect immediately if the connection is broken
  Future<void> appActive();

  Future<void> connect();

  String get connectionStatus;

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Client> newInstance(
          {required AuthInfo info, String? rootPath, String? dbName}) =>
      RustLib.instance.api.crateClientClientClientNew(
          info: info, rootPath: rootPath, dbName: dbName);

  set keepalive(int secs);

  Future<void> shutdown();
}
