use sea_orm::{Database, DatabaseConnection, DbErr};
use sea_orm_migration::prelude::*;

pub async fn connect_db(database_url: &str) -> Result<DatabaseConnection, DbErr> {
    Database::connect(database_url).await
}

pub async fn run_migrations(db: &DatabaseConnection) -> Result<(), DbErr> {
    Migrator::up(db, None).await
}

pub struct Migrator;

#[async_trait::async_trait]
impl MigratorTrait for Migrator {
    fn migrations() -> Vec<Box<dyn MigrationTrait>> {
        vec![Box::new(InitSchema), Box::new(HelpdeskSchema)]
    }
}

struct InitSchema;

impl MigrationName for InitSchema {
    fn name(&self) -> &str {
        "m20260508_000001_init_schema"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for InitSchema {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Users::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Users::UserId)
                            .string_len(191)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Users::Password)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Users::DisplayName)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(ColumnDef::new(Users::Avatar).text().not_null().default(""))
                    .col(ColumnDef::new(Users::Source).text().not_null().default(""))
                    .col(ColumnDef::new(Users::Locale).text().not_null().default(""))
                    .col(ColumnDef::new(Users::City).text().not_null().default(""))
                    .col(ColumnDef::new(Users::Country).text().not_null().default(""))
                    .col(ColumnDef::new(Users::Gender).text().not_null().default(""))
                    .col(
                        ColumnDef::new(Users::PublicKey)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Users::IsStaff)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Users::Enabled)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(ColumnDef::new(Users::CreatedAt).text().not_null())
                    .col(ColumnDef::new(Users::UpdatedAt).text().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Topics::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Topics::Id)
                            .string_len(191)
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Topics::Name).text().not_null().default(""))
                    .col(ColumnDef::new(Topics::Icon).text().not_null().default(""))
                    .col(ColumnDef::new(Topics::Kind).text().not_null().default(""))
                    .col(
                        ColumnDef::new(Topics::OwnerId)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Topics::AttendeeId)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Topics::Members)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(Topics::LastSeq)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(Topics::Multiple)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(ColumnDef::new(Topics::Source).text().not_null().default(""))
                    .col(
                        ColumnDef::new(Topics::Private)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Topics::KnockNeedVerify)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Topics::AdminsJson)
                            .text()
                            .not_null()
                            .default("[]"),
                    )
                    .col(
                        ColumnDef::new(Topics::WebhooksJson)
                            .text()
                            .not_null()
                            .default("[]"),
                    )
                    .col(
                        ColumnDef::new(Topics::NoticeJson)
                            .text()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(Topics::ExtraJson)
                            .text()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(Topics::SilentWhiteListJson)
                            .text()
                            .not_null()
                            .default("[]"),
                    )
                    .col(
                        ColumnDef::new(Topics::Silent)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Topics::Enabled)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(ColumnDef::new(Topics::CreatedAt).text().not_null())
                    .col(ColumnDef::new(Topics::UpdatedAt).text().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Conversations::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Conversations::OwnerId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Conversations::TopicId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(ColumnDef::new(Conversations::UpdatedAt).text().not_null())
                    .col(
                        ColumnDef::new(Conversations::Sticky)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Conversations::Mute)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(ColumnDef::new(Conversations::Remark).text())
                    .col(
                        ColumnDef::new(Conversations::Unread)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(Conversations::StartSeq)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(Conversations::LastSeq)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(Conversations::LastReadSeq)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(Conversations::LastReadAt).text())
                    .col(
                        ColumnDef::new(Conversations::Multiple)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Conversations::Attendee)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Conversations::Members)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(Conversations::Name)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Conversations::Icon)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Conversations::Kind)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Conversations::Source)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Conversations::LastSenderId)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Conversations::LastMessageJson)
                            .text()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(Conversations::LastMessageAt)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Conversations::LastMessageSeq)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .primary_key(
                        Index::create()
                            .col(Conversations::OwnerId)
                            .col(Conversations::TopicId),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(TopicMembers::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(TopicMembers::TopicId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TopicMembers::UserId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TopicMembers::Name)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(TopicMembers::Source)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(TopicMembers::Role)
                            .text()
                            .not_null()
                            .default("member"),
                    )
                    .col(ColumnDef::new(TopicMembers::SilenceAt).text())
                    .col(ColumnDef::new(TopicMembers::JoinedAt).text().not_null())
                    .col(ColumnDef::new(TopicMembers::UpdatedAt).text().not_null())
                    .col(
                        ColumnDef::new(TopicMembers::ExtraJson)
                            .text()
                            .not_null()
                            .default("{}"),
                    )
                    .primary_key(
                        Index::create()
                            .col(TopicMembers::TopicId)
                            .col(TopicMembers::UserId),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ChatLogs::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ChatLogs::Id)
                            .string_len(191)
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(ChatLogs::TopicId).string_len(191).not_null())
                    .col(ColumnDef::new(ChatLogs::Seq).big_integer().not_null())
                    .col(
                        ColumnDef::new(ChatLogs::SenderId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(ColumnDef::new(ChatLogs::ContentJson).text().not_null())
                    .col(
                        ColumnDef::new(ChatLogs::DeletedByJson)
                            .text()
                            .not_null()
                            .default("[]"),
                    )
                    .col(
                        ColumnDef::new(ChatLogs::Read)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ChatLogs::Recall)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ChatLogs::Source)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(ColumnDef::new(ChatLogs::CreatedAt).text().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Relations::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Relations::OwnerId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Relations::TargetId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Relations::IsContact)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Relations::IsStar)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Relations::IsBlocked)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Relations::Remark)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Relations::Source)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(ColumnDef::new(Relations::UpdatedAt).text().not_null())
                    .primary_key(
                        Index::create()
                            .col(Relations::OwnerId)
                            .col(Relations::TargetId),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(TopicKnocks::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(TopicKnocks::TopicId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TopicKnocks::UserId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(ColumnDef::new(TopicKnocks::CreatedAt).text().not_null())
                    .col(ColumnDef::new(TopicKnocks::UpdatedAt).text().not_null())
                    .col(
                        ColumnDef::new(TopicKnocks::Message)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(TopicKnocks::Source)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(TopicKnocks::Status)
                            .text()
                            .not_null()
                            .default("pending"),
                    )
                    .col(
                        ColumnDef::new(TopicKnocks::AdminId)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .primary_key(
                        Index::create()
                            .col(TopicKnocks::TopicId)
                            .col(TopicKnocks::UserId),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(AuthTokens::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AuthTokens::Token)
                            .string_len(191)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(AuthTokens::UserId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(ColumnDef::new(AuthTokens::CreatedAt).text().not_null())
                    .col(ColumnDef::new(AuthTokens::LastSeenAt).text().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(PresenceSessions::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(PresenceSessions::UserId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PresenceSessions::Device)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PresenceSessions::NodeId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PresenceSessions::Endpoint)
                            .string_len(191)
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(PresenceSessions::UpdatedAtUnix)
                            .big_integer()
                            .not_null(),
                    )
                    .primary_key(
                        Index::create()
                            .col(PresenceSessions::UserId)
                            .col(PresenceSessions::Device),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Attachments::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Attachments::Path)
                            .string_len(191)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Attachments::FileName)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Attachments::StorePath)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Attachments::OwnerId)
                            .string_len(191)
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Attachments::TopicId)
                            .string_len(191)
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Attachments::Size)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(Attachments::Ext)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Attachments::Private)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Attachments::External)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Attachments::Tags)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Attachments::Remark)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(ColumnDef::new(Attachments::CreatedAt).text().not_null())
                    .to_owned(),
            )
            .await?;

        if !manager.has_column("users", "password").await? {
            manager
                .alter_table(
                    Table::alter()
                        .table(Users::Table)
                        .add_column(
                            ColumnDef::new(Users::Password)
                                .text()
                                .not_null()
                                .default(""),
                        )
                        .to_owned(),
                )
                .await?;
        }

        if !manager.has_column("users", "enabled").await? {
            manager
                .alter_table(
                    Table::alter()
                        .table(Users::Table)
                        .add_column(
                            ColumnDef::new(Users::Enabled)
                                .boolean()
                                .not_null()
                                .default(true),
                        )
                        .to_owned(),
                )
                .await?;
        }

        if !manager.has_column("topics", "enabled").await? {
            manager
                .alter_table(
                    Table::alter()
                        .table(Topics::Table)
                        .add_column(
                            ColumnDef::new(Topics::Enabled)
                                .boolean()
                                .not_null()
                                .default(true),
                        )
                        .to_owned(),
                )
                .await?;
        }

        if !manager.has_column("presence_sessions", "endpoint").await? {
            manager
                .alter_table(
                    Table::alter()
                        .table(PresenceSessions::Table)
                        .add_column(
                            ColumnDef::new(PresenceSessions::Endpoint)
                                .string_len(191)
                                .not_null()
                                .default(""),
                        )
                        .to_owned(),
                )
                .await?;
        }

        manager
            .create_index(
                Index::create()
                    .name("idx_conversations_owner_updated")
                    .table(Conversations::Table)
                    .if_not_exists()
                    .col(Conversations::OwnerId)
                    .col(Conversations::UpdatedAt)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_chat_logs_topic_seq")
                    .table(ChatLogs::Table)
                    .if_not_exists()
                    .col(ChatLogs::TopicId)
                    .col(ChatLogs::Seq)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_topic_members_user")
                    .table(TopicMembers::Table)
                    .if_not_exists()
                    .col(TopicMembers::UserId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_auth_tokens_user")
                    .table(AuthTokens::Table)
                    .if_not_exists()
                    .col(AuthTokens::UserId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_presence_node_updated")
                    .table(PresenceSessions::Table)
                    .if_not_exists()
                    .col(PresenceSessions::NodeId)
                    .col(PresenceSessions::UpdatedAtUnix)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_attachments_owner")
                    .table(Attachments::Table)
                    .if_not_exists()
                    .col(Attachments::OwnerId)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(Attachments::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(PresenceSessions::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(AuthTokens::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(TopicKnocks::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(Relations::Table).if_exists().to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ChatLogs::Table).if_exists().to_owned())
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(TopicMembers::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Conversations::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(Topics::Table).if_exists().to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Users::Table).if_exists().to_owned())
            .await?;

        Ok(())
    }
}

#[derive(DeriveIden)]
enum Users {
    Table,
    UserId,
    Password,
    DisplayName,
    Avatar,
    Source,
    Locale,
    City,
    Country,
    Gender,
    PublicKey,
    IsStaff,
    Enabled,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum Topics {
    Table,
    Id,
    Name,
    Icon,
    Kind,
    OwnerId,
    AttendeeId,
    Members,
    LastSeq,
    Multiple,
    Source,
    Private,
    KnockNeedVerify,
    AdminsJson,
    WebhooksJson,
    NoticeJson,
    ExtraJson,
    SilentWhiteListJson,
    Silent,
    Enabled,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum Conversations {
    Table,
    OwnerId,
    TopicId,
    UpdatedAt,
    Sticky,
    Mute,
    Remark,
    Unread,
    StartSeq,
    LastSeq,
    LastReadSeq,
    LastReadAt,
    Multiple,
    Attendee,
    Members,
    Name,
    Icon,
    Kind,
    Source,
    LastSenderId,
    LastMessageJson,
    LastMessageAt,
    LastMessageSeq,
}

#[derive(DeriveIden)]
enum TopicMembers {
    Table,
    TopicId,
    UserId,
    Name,
    Source,
    Role,
    SilenceAt,
    JoinedAt,
    UpdatedAt,
    ExtraJson,
}

#[derive(DeriveIden)]
enum ChatLogs {
    Table,
    Id,
    TopicId,
    Seq,
    SenderId,
    ContentJson,
    DeletedByJson,
    Read,
    Recall,
    Source,
    CreatedAt,
}

#[derive(DeriveIden)]
enum Relations {
    Table,
    OwnerId,
    TargetId,
    IsContact,
    IsStar,
    IsBlocked,
    Remark,
    Source,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum TopicKnocks {
    Table,
    TopicId,
    UserId,
    CreatedAt,
    UpdatedAt,
    Message,
    Source,
    Status,
    AdminId,
}

#[derive(DeriveIden)]
enum AuthTokens {
    Table,
    Token,
    UserId,
    CreatedAt,
    LastSeenAt,
}

#[derive(DeriveIden)]
enum PresenceSessions {
    Table,
    UserId,
    Device,
    NodeId,
    Endpoint,
    UpdatedAtUnix,
}

#[derive(DeriveIden)]
enum Attachments {
    Table,
    Path,
    FileName,
    StorePath,
    OwnerId,
    TopicId,
    Size,
    Ext,
    Private,
    External,
    Tags,
    Remark,
    CreatedAt,
}

#[derive(DeriveIden)]
enum HelpdeskInboxes {
    Table,
    Id,
    Name,
    DisplayName,
    Type,
    WidgetConfigJson,
    Greeting,
    GreetingEnabled,
    RoutingStrategy,
    OfflineEmail,
    OfflineWebhookUrl,
    OfflineWebhookSecret,
    IsActive,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum HelpdeskInboxMembers {
    Table,
    InboxId,
    UserId,
    Role,
    CreatedAt,
}

struct HelpdeskSchema;

impl MigrationName for HelpdeskSchema {
    fn name(&self) -> &str {
        "m20260512_000001_helpdesk"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for HelpdeskSchema {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(HelpdeskInboxes::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(HelpdeskInboxes::Id)
                            .string_len(191)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(HelpdeskInboxes::Name)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(HelpdeskInboxes::DisplayName)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(HelpdeskInboxes::Type)
                            .text()
                            .not_null()
                            .default("web"),
                    )
                    .col(
                        ColumnDef::new(HelpdeskInboxes::WidgetConfigJson)
                            .text()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(HelpdeskInboxes::Greeting)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(HelpdeskInboxes::GreetingEnabled)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(HelpdeskInboxes::RoutingStrategy)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(HelpdeskInboxes::OfflineEmail)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(HelpdeskInboxes::OfflineWebhookUrl)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(HelpdeskInboxes::OfflineWebhookSecret)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(HelpdeskInboxes::IsActive)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(ColumnDef::new(HelpdeskInboxes::CreatedAt).text().not_null())
                    .col(ColumnDef::new(HelpdeskInboxes::UpdatedAt).text().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(HelpdeskInboxMembers::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(HelpdeskInboxMembers::InboxId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HelpdeskInboxMembers::UserId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HelpdeskInboxMembers::Role)
                            .text()
                            .not_null()
                            .default("agent"),
                    )
                    .col(
                        ColumnDef::new(HelpdeskInboxMembers::CreatedAt)
                            .text()
                            .not_null(),
                    )
                    .primary_key(
                        Index::create()
                            .col(HelpdeskInboxMembers::InboxId)
                            .col(HelpdeskInboxMembers::UserId),
                    )
                    .to_owned(),
            )
            .await?;

        // create a default inbox
        let now = chrono::Utc::now().to_rfc3339();
        let insert = sea_orm::sea_query::Query::insert()
            .into_table(HelpdeskInboxes::Table)
            .columns([
                HelpdeskInboxes::Id,
                HelpdeskInboxes::Name,
                HelpdeskInboxes::DisplayName,
                HelpdeskInboxes::Type,
                HelpdeskInboxes::CreatedAt,
                HelpdeskInboxes::UpdatedAt,
            ])
            .values_panic([
                "inbox_default".into(),
                "default".into(),
                "默认 Inbox".into(),
                "web".into(),
                now.clone().into(),
                now.into(),
            ])
            .to_owned();
        manager.exec_stmt(insert).await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(HelpdeskInboxMembers::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(HelpdeskInboxes::Table).to_owned())
            .await?;
        Ok(())
    }
}
